host: localhost:8080
info:
  contact: {}
  description: This is a sample API for demonstration purposes. It includes multiple
    endpoints for various operations.
  title: Your API Title
  version: "1.0"
paths:
  /api/route:
    get:
      responses: {}
  /home/DirectPurchase:
    post:
      consumes:
      - application/json
      parameters:
      - description: 收件地址
        in: formData
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "2003":
          description: （直接购买）购买成功
          schema:
            type: string
        "4002":
          description: 密码错误
          schema:
            type: string
        "4014":
          description: 无对应书籍
          schema:
            type: string
      tags:
      - 购物
  /home/PurchaseFromSC:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 电子邮件
        in: formData
        name: email
        type: string
      produces:
      - application/json
      responses:
        "2000":
          description: 登录成功
          schema:
            type: string
        "4008":
          description: 用户余额不足
          schema:
            type: string
        "4013":
          description: 购物车为空
          schema:
            type: string
      tags:
      - 购物
  /home/ShoppingCarts/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 书籍的ISBN编号
        in: query
        name: ISBN
        required: true
        type: string
      - description: 出售者用户名
        in: query
        name: SellerName
        required: true
        type: string
      - description: 当前用户名
        in: query
        name: userName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "2009":
          description: 添加成功
          schema:
            type: string
        "4009":
          description: 添加失败
          schema:
            type: string
        "5002":
          description: 数据绑定失败
          schema:
            type: string
      summary: 添加书籍到购物车
      tags:
      - 购物
  /home/ShoppingCarts/remove:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 书籍的ISBN编号
        in: query
        name: ISBN
        required: true
        type: string
      - description: 出售者用户名
        in: query
        name: SellerName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "2010":
          description: 删除成功
          schema:
            type: string
        "4010":
          description: 从购物车删除失败
          schema:
            type: string
        "5001":
          description: 非法图书ID
          schema:
            type: string
      summary: 将书籍从购物车清除
      tags:
      - 购物
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 电子邮件
        in: formData
        name: email
        type: string
      produces:
      - application/json
      responses:
        "2000":
          description: 登录成功
          schema:
            type: string
        "4001":
          description: 该用户不存在
          schema:
            type: string
        "4002":
          description: 密码错误
          schema:
            type: string
      tags:
      - 登录
  /register:
    post:
      consumes:
      - application/json
      description: 注册一个新用户账号
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: confirmPassword
        required: true
        type: string
      - description: 电子邮件
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            type: string
        "400":
          description: 该用户名已被使用
          schema:
            type: string
        "422":
          description: 用户名不能为空
          schema:
            type: string
        "500":
          description: 密码加密错误
          schema:
            type: string
        "4003":
          description: 重复密码与第一次输入的密码不一致，请重新输入
          schema:
            type: string
      summary: 注册新用户
      tags:
      - 登录
swagger: "2.0"
